local library = loadstring(game:HttpGet(('https://raw.githubusercontent.com/AikaV3rm/UiLib/master/Lib.lua')))()

local w = library:CreateWindow("Shoe Simulator") -- Creates the window

local b = w:CreateFolder("FarmList") -- Creates the folder(U will put here your buttons,etc)

local r = w:CreateFolder("PlayerOptions")

local o = w:CreateFolder("TeleportOption")

local c = w:CreateFolder("Other")

b:Button("AutoCollect ON",function()
    _G.AutoClick = true
    while _G.AutoClick == true do
wait(0)
-- Script generated by SimpleSpy - credits to exx#9394

local args = {
[1] = {
    [1] = "PickupShoe",
    [2] = "Starter",
    [3] = Vector3.new(440.92333984375, 0.99999988079071, -103.84445953369),
    [4] = "Youtube Shoes"
}
}

game:GetService("ReplicatedStorage").Events.Collect:FireServer(unpack(args))


    end
end)

b:Button("AutoCollect OFF",function()
    _G.AutoClick = false
    while _G.AutoClick == true do
wait(0)
-- Script generated by SimpleSpy - credits to exx#9394

local args = {
[1] = {
    [1] = "PickupShoe",
    [2] = "Starter",
    [3] = Vector3.new(440.92333984375, 0.99999988079071, -103.84445953369),
    [4] = "Youtube Shoes"
}
}

game:GetService("ReplicatedStorage").Events.Collect:FireServer(unpack(args))


    end
end)

b:Button("SellButton",function()
    _G.AutoSell = true
    while _G.AutoClick == true do
        wait(0.1)
        -- Script generated by SimpleSpy - credits to exx#9394
        
        local args = {
            [1] = {
                [1] = "Sell"
            }
        }
        
        game:GetService("ReplicatedStorage").Events.Teleport:FireServer(unpack(args))
        wait(0.5)
        -- Script generated by SimpleSpy - credits to exx#9394
        
        local args = {
            [1] = {
                [1] = "Screen",
                [2] = workspace.SellPlaces.Snow
            }
        }
        
        game:GetService("ReplicatedStorage").Events.Click:FireServer(unpack(args))
        

    end

end)

b:Button("SellButton OFF",function()
    _G.AutoSell = false
    while _G.AutoClick == true do
        wait(0.1)
        -- Script generated by SimpleSpy - credits to exx#9394
        
        local args = {
            [1] = {
                [1] = "Sell"
            }
        }
        
        game:GetService("ReplicatedStorage").Events.Teleport:FireServer(unpack(args))
        wait(0.5)
        -- Script generated by SimpleSpy - credits to exx#9394
        
        local args = {
            [1] = {
                [1] = "Screen",
                [2] = workspace.SellPlaces.Snow
            }
        }
        
        game:GetService("ReplicatedStorage").Events.Click:FireServer(unpack(args))
        

    end

end)

c:DestroyGui()


